import  slika from './planet-earth-space.jpg'
const initialState = {
    user:{    
        "login": "JasnaJ",
        "id": 1,
        "node_id": "MDQ6VXNlcjE=",
        "avatar_url": slika,
        "gravatar_id": "",
        "url": "https://api.github.com/users/JasnaJ",
        "html_url": "https://github.com/mojombo",
        "followers_url": "https://api.github.com/users/mojombo/followers",
        "following_url": "https://api.github.com/users/mojombo/following{/other_user}",
        "gists_url": "https://api.github.com/users/mojombo/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mojombo/subscriptions",
        "organizations_url": "https://api.github.com/users/mojombo/orgs",
        "repos_url": "https://api.github.com/users/mojombo/repos",
        "events_url": "https://api.github.com/users/mojombo/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mojombo/received_events",
        "type": "User",
        "site_admin": false,
        "name": "Jasna Jovanic",
        "company": "working at home ",
        "blog": "http://tom.preston-werner.com",
        "location": "Novi Sad",
        "email": "jovanic_jasna@yahoo.com",
        "hireable": null,
        "bio": null,
        "twitter_username": "mojombo",
        "public_repos": 3,
        "public_gists": 62,
        "followers": 215,
        "following": 89,
        "created_at": "2007-10-20T05:24:19Z",
        "updated_at": "2022-01-21T00:10:18Z"
    },
    repos:[
        {
            "id": 26899533,
            "name": "calculator.github.io",
            "owner": {
                "login": "JasnaJ",
                "id": 1,
            },
            "description": null,
            "stargazers_count": 7,
            "language": "#C",
            "forks_count": 2,
            "visibility": "public",
            "forks": 2,
        },
        {
            "id": 598741325,
            "name": "parking.github.io",
            "owner": {
                "login": "JasnaJ",
                "id": 1,
            },
            "description": null,
            "stargazers_count": 89,
            "language": "CSS",
            "visibility": "public",
            "forks": 13,
        },
        {
            "id": 78451236,
            "name": "haircut_salon.github.io",
            "owner": {
                "login": "JasnaJ",
                "id": 1,
            },
            "description": null,
            "stargazers_count": 3,
            "language": "JavaScript",
            "visibility": "public",
            "forks": 1,
        },
    ]

}
export default initialState;